version: "3.2"

services:
  mongo1:
    container_name: mongo1
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all"]
    restart: always
    ports:
      - 27017:27017
    networks:
      mongo-cluster:
        ipv4_address: 111.222.32.2

  mongo2:
    image: mongo:latest
    container_name: mongo2
    command: ["--replSet", "rs0" ,"--bind_ip_all"]
    restart: always
    ports:
      - 27018:27017
    networks:
      mongo-cluster:
        ipv4_address: 111.222.32.3

  mongo3:
    image: mongo:latest
    container_name: mongo3
    command: ["--replSet", "rs0" ,"--bind_ip_all"]
    restart: always
    ports:
      - 27019:27017
    networks:
      mongo-cluster:
        ipv4_address: 111.222.32.4



volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:

networks:
  mongo-cluster:
    ipam:
      config:
        - subnet: 111.222.32.0/24